
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbpbwijovpfyqbxgtaiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNicGJ3aWpvdnBmeXFieGd0YWl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1ODI1MDYsImV4cCI6MjA2MDE1ODUwNn0.kqBCi3gzQjuF7ZhaS6yf8XYdYIfpG96YBNo5hfnELUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true
  }
});
